[package]
name = "bevy_simple_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."*"]
opt-level = 3
# rustflags = ["-C","target-cpu=native"]

[profile.release]
lto = "thin"

[dependencies]
bevy-inspector-egui = {version = "0.18.3", default-features = false}
# bevy dependency below
bracket-random = "^0.8"

[dependencies.bevy]
version = "^0.10"
default-features = false
features = [
  # if you add dynamic linking, remember not to commit

  # instead of dynamic linking, if working on linux, on a fairly recent computer I recomend using 
  # mold linker. I have found that recompiling debug with mold and rust 1.69 
  # (likely because of newly enabled incremental builds)  
  # has nearly negligible speed differences from recompiling debug with dynamic_lib

  # bevy features we (probably) make use of 
  "bevy_asset",
  "bevy_core_pipeline",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_winit",
  "bevy_ui",
  "subpixel_glyph_atlas",

  "png", 

  # support both to be safe. If you're building for yourself you probably know which one to remove
  "x11",
  "wayland"
]

