[package]
name = "bevy_simple_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."*"]
opt-level = 3
# rustflags = ["-C","target-cpu=native"]

[profile.release]
lto = "thin"

[dependencies]
bracket-random = "^0.8"

[dependencies.bevy]
version = "^0.10"
default-features = false
features = [
  # "dynamic_linking", # comment out for release builds 

  # bevy features we make use of 
  "bevy_asset",
  "bevy_core_pipeline",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_winit",
  "bevy_ui",
  "subpixel_glyph_atlas",

  "png", 

  # support both to be safe. If you're building for yourself you probably know which one to remove
  "x11",
  "wayland"
]

