[package]
name = "bevy_simple_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package."*"]
opt-level = 3
# rustflags = ["-Ctarget-cpu=native"]

[dependencies]
# TODO: strip out shit like pbr that we clearly do not need
bevy = {version = "^0.10", features = ["dynamic_linking","wayland"]}
bracket-random = "^0.8"
# bevy = "^0.10"


